### ISSUE TITLE
升flutter 2.0后报错

### ISSUE THREAD

**Issue by Ampy** [peng8350/flutter_pulltorefresh#447]
升级flutter sdk 到2.0版本后，编译报错了。

**Comment by weiweilidd01** [comment]
报错内容： ../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.3/lib/src/smart_refresher.dart:1003:20: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
    return context.inheritFromWidgetOfExactType(RefreshConfiguration);

**Comment by hongfeiyang** [comment]
我解决了，从1.6.3升级到1.6.4 然后flutter pub cache repair一下就好了

**Comment by nietsmmar** [comment]
> 我解决了，从1.6.3升级到1.6.4 然后flutter clean && flutter pub cache repair一下就好了

I got the same error and this does not help. But I can't read your whole answer as there are some characters that won't display on my machine. You just did flutter clean and pub cache repair?

I am using version 1.6.3 because 1.6.4 has this bug https://github.com/peng8350/flutter_pulltorefresh/issues/427

But it just won't work  because of the `Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.`  error.

Has anyone a solution?

**Comment by hongfeiyang** [comment]
> > 我解决了，从1.6.3升级到1.6.4 然后flutter clean && flutter pub cache repair一下就好了
> 
> 
> 
> I got the same error and this does not help. But I can't read your whole answer as there are some characters that won't display on my machine. You just did flutter clean and pub cache repair?
> 
> 
> 
> I am using version 1.6.3 because 1.6.4 has this bug https://github.com/peng8350/flutter_pulltorefresh/issues/427
> 
> 
> 
> But it just won't work  because of the `Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.`  error.
> 
> 
> 
> Has anyone a solution?

1.6.3 is only compatible with flutter < 2.0 and and 1.6.4 is only compatible with flutter >= 2.0. I guess you have no choice other than to use 1.6.4 on flutter 2.0
